apiVersion: v2
appVersion: "2.1.36"
description: JOAL is not designed to help or encourage you downloading illegal materials ! You must respect the law applicable in your country. I couldn't be held responsible for illegal activities performed by your usage of JOAL.
name: joal
version: "1.0.0"
icon: https://spirit-dev.github.io/test-helm/joal/logo/joal.png
home: https://github.com/spirit-dev/test-helm
keywords:
  - torrent
  - joal
sources:
  - https://github.com/spirit-dev/test-helm
