apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "joal.fullname" . }}
  labels:
    app: {{ template "joal.name" . }}
    chart: {{ template "joal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "joal.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "joal.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{ toYaml .Values.env | indent 12 }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
